# 20819A1 firmware build 230
# patch entries used: 87 out of 256 elf patches, 33%
CY_PATCH_ENTRIES_BASE=87
# additional patch entries in these libraries:
#   2 in cfa_mm_alloc_free_replace_lib.a
#   8 in wiced_ble_connect_timing_lib.a
#   4 in wiced_uart_raw_mode_lib.a
#   7 in multi_adv_lib.a
#   2 in mesh_optimized_continuous_scan_lib.a
#   1 in dbfw_lib.a
#   4 in wiced_audio_source_lib.a
#   6 in mpaf_lib.a
#   1 in wiced_hidd_lib.a
# patch ram used: 14768 out of 15360 bytes, 96%
