# 20819A1 firmware build 264
# patch entries used: 23 out of 256 elf patches, 8%
CY_PATCH_ENTRIES_BASE=23
# additional patch entries in these libraries:
#   1 in wiced_bt_ble_lib.a
#   19 in bt_lib.a
#   2 in mesh_optimized_continuous_scan_lib.a
#   3 in wiced_hal_lib.a
#   2 in cfa_mm_alloc_free_replace_lib.a
#   4 in wiced_audio_source_lib.a
#   3 in wiced_blurtooth_lib.a
#   4 in wiced_uart_raw_mode_lib.a
#   7 in ble_antenna_diversity_lib.a
#   28 in foundation_lib.a
#   1 in adva_lib.a
#   23 in mpaf_lib.a
#   2 in wiced_hidd_lib.a
#   7 in multi_adv_lib.a
#   8 in wiced_ble_connect_timing_lib.a
#   1 in dbfw_lib.a
#   6 in wiced_rf_lib.a
# patch ram used: 2856 out of 15360 bytes, 18%
