# 20819A1 firmware build 140
# patch entries used: 78 out of 256 elf patches, 30%
CY_PATCH_ENTRIES_BASE=78
# additional patch entries in these libraries:
#   2 in cfa_mm_alloc_free_replace_lib.a
#   1 in wiced_hidd_lib.a
#   1 in dbfw_lib.a
#   4 in wiced_audio_source_lib.a
#   4 in wiced_uart_raw_mode_lib.a
#   2 in mesh_optimized_continuous_scan_lib.a
#   7 in multi_adv_lib.a
# patch ram used: 15100 out of 15360 bytes, 98%
